/**
 * Common error code constants (API-002).
 * Machine-readable codes used in all error responses.
 */
export const ErrorCodes = {
  // ── Auth ──
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_SESSION_INVALID: 'AUTH_SESSION_INVALID',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',

  // ── Authorization ──
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
  RESOURCE_NOT_OWNED: 'RESOURCE_NOT_OWNED',
  ELEVATED_CONFIRMATION_REQUIRED: 'ELEVATED_CONFIRMATION_REQUIRED',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',

  // ── Validation ──
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  // ── Rate Limiting ──
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // ── Idempotency ──
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',

  // ── State Machine ──
  INVALID_ACTION: 'INVALID_ACTION',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  REASON_REQUIRED: 'REASON_REQUIRED',

  // ── Money ──
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  PRIZE_POOL_MISMATCH: 'PRIZE_POOL_MISMATCH',

  // ── Tournament ──
  TOURNAMENT_MODE_IMMUTABLE: 'TOURNAMENT_MODE_IMMUTABLE',
  SCORING_LOCKED: 'SCORING_LOCKED',
  CAPACITY_EXCEEDED: 'CAPACITY_EXCEEDED',

  // ── Registration ──
  ALREADY_REGISTERED: 'ALREADY_REGISTERED',
  ROSTER_INCOMPLETE: 'ROSTER_INCOMPLETE',
  ROSTER_LOCKED: 'ROSTER_LOCKED',
  PLAYER_INELIGIBLE: 'PLAYER_INELIGIBLE',

  // ── Results ──
  DUPLICATE_PLACEMENT: 'DUPLICATE_PLACEMENT',
  INVALID_PLACEMENT: 'INVALID_PLACEMENT',
  RESULT_ALREADY_FINALIZED: 'RESULT_ALREADY_FINALIZED',

  // ── Provider ──
  PROVIDER_ERROR: 'PROVIDER_ERROR',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',

  // ── Internal ──
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
